apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo the app is running && sleep 30']
    env:
    - name: FIRSTNAME
      value: "Krupa"
initContainers:   # depending on service created.
- name: init-myservice
  command: ['sh' , '-c']
  args: ['until ns lookup myservice.default.svc.cluster.local; do echo "waiting for service to be up"; sleep 2; done'] # until this command returns the result, do something.
